### ISSUE TITLE
東京都のレポジトリ上の秋田版へのリンクを更新する

### ISSUE THREAD

**Issue by nard-tech** [code4akita/covid19-akita#94]
## 改善詳細 / Details of Improvement
- issue: https://github.com/tokyo-metropolitan-gov/covid19/issues/6094
- PR: https://github.com/tokyo-metropolitan-gov/covid19/pull/6095 

## 期待する見せ方・挙動 / Expected behavior
- https://github.com/tokyo-metropolitan-gov/covid19/blob/development/FORKED_SITES.md のリンクを更新する

----

東京都のレポジトリ上の秋田版へのリンクについて変更の PR が出されている (https://github.com/tokyo-metropolitan-gov/covid19/pull/6095) が，

> こちら、秋田県のサイトの関係者からのご提案であれば受け付けたいと思います。

(https://github.com/tokyo-metropolitan-gov/covid19/issues/6094) とのことなので，https://github.com/tokyo-metropolitan-gov/covid19/issues/6094 に運営の方が一言更新するように書き込んで欲しい．

**Comment by nard-tech** [comment]
東京都版にコミットしつつ，秋田のお隣の岩手版にも関わっている者です．

tokyo-metropolitan-gov#6094, tokyo-metropolitan-gov#6095 を見て，こちらに issue を立てさせて頂きました．よろしくお願いします．

**Comment by dzonesasaki** [comment]
ご提案ありがとうございます。
前のバージョンである https://covid19-akita.netlify.app/ から、Code for Akitaが引き継いで、https://covid19-akita-cfa.netlify.app/ を更新しています。
つまり、https://github.com/tokyo-metropolitan-gov/covid19/blob/development/FORKED_SITES.md を修正して、プッシュすれば良いでしょうか？

**Comment by dzonesasaki** [comment]
教えて頂きたいのですが、pull requestには何を書いたら良いのでしょうか？今回のissue番号は何番なのかが判りません。
まずは、https://github.com/tokyo-metropolitan-gov/covid19/blob/development/FORKED_SITES.md  を修正して、変更提案( proposal ～～～ のボタンを押下) までは行いました。

**Comment by suzuryo** [comment]
今回のissue番号は、東京版の 6094 ( https://github.com/tokyo-metropolitan-gov/covid19/issues/6094 )  なので東京版にpull requestを建てるときに `#6094` と書けばOKです

**Comment by dzonesasaki** [comment]
@suzuryo さん、ありがとうございます！！

**Comment by dzonesasaki** [comment]
現在、今朝とは違う端末のためなのか、修正後のページ（pull requestのボタンが出ているページ）が出てこず、アタフタしています。今朝使った端末(自宅)で、再びそれが出るのかも不安です。。。 ;_;

**Comment by suzuryo** [comment]
@dzonesasaki 
お、東京版にプルリクエスト出ましたね。
https://github.com/tokyo-metropolitan-gov/covid19/pull/6181

本文がテンプレのままなので、

```
解決する
- close #6094

変更内容
- 秋田版のURL更新

```

とテンプレを修正して分かりやすく記載するよ良いかも？

**Comment by dzonesasaki** [comment]
ありがとうございます！！
ただ、修正してみたのですが、あれで良いのか。。。。
本件に関連したissueが複数あったように思えて、それも加えると良いんですよね？

**Comment by suzuryo** [comment]
そうですね。関連issueがあれば

```
関連する
```

に追加しても良いかもです。

**Comment by dzonesasaki** [comment]
@suzuryo さん、ありがとうございます！！助かりました！

**Comment by katsuyoshi** [comment]
mergeされているのでcloseします。
みなさんありがとうございます。
